# Generated by Django 3.2 on 2021-08-16 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日付')),
                ('title', models.CharField(max_length=20, verbose_name='ジャンル')),
                ('published', models.DateTimeField()),
                ('text', models.TextField(max_length=200, verbose_name='問題内容')),
                ('answer', models.TextField(max_length=200, verbose_name='その答え')),
            ],
        ),
    ]
