# Generated by Django 3.2.6 on 2021-08-23 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210820_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
