# Generated by Django 3.2.6 on 2021-08-28 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='choice',
        ),
        migrations.AddField(
            model_name='post',
            name='pulldown',
            field=models.CharField(choices=[('0', 'Linux'), ('1', 'Web'), ('2', 'Network'), ('3', 'programming'), ('4', 'PC操作'), ('5', 'その他')], default=1, max_length=10, verbose_name='ジャンル'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='通知日時'),
        ),
    ]
