# Generated by Django 3.2.5 on 2021-08-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210828_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference',
            field=models.URLField(blank=True, null=True, verbose_name='参考URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pulldown',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Web', 'Web'), ('Network', 'Network'), ('プログラミング', 'Programming'), ('PC操作', 'PC操作'), ('その他', 'その他')], max_length=10, verbose_name='ジャンル'),
        ),
    ]
