# Generated by Django 3.2 on 2021-09-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210831_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(max_length=100, verbose_name='問題の答え'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=100, verbose_name='問題内容'),
        ),
    ]
